COMMENT =		on the fly conversion of Python docstrings to markdown

MODPY_EGG_VERSION =	0.12
DISTNAME =		docstring-to-markdown-${MODPY_EGG_VERSION}
PKGNAME =		py-docstring-to-markdown-${MODPY_EGG_VERSION}

CATEGORIES =		textproc

HOMEPAGE =		https://github.com/python-lsp/docstring-to-markdown

MAINTAINER =		Laurent Cheylus <foxy@free.fr>

# LGPLv2.1
PERMIT_PACKAGE =	Yes

MODULES =		lang/python

FLAVORS =		python3
FLAVOR =		python3

MODPY_PI =		Yes
MODPY_PYBUILD =		setuptools

# Incompatible tests with flake8>5 and issues with pytest-flake8 package
NO_TEST =		Yes

.include <bsd.port.mk>
