COMMENT=		Perl modules for processing SGML parser output
DISTNAME=		SGMLSpm-1.03ii
PKGNAME=		p5-${DISTNAME}
CATEGORIES=		textproc

MAINTAINER=		chara <chara@cloud9p.org>

# perl
PERMIT_PACKAGE=	Yes

SITES=		https://cpan.metacpan.org/authors/id/D/DM/DMEGG/

WRKDIST=	${WRKDIR}/SGMLSpm
NO_BUILD=	Yes

.include <bsd.port.mk>
