COMMENT=		Simpler interface to WWW::Curl

MODULES=		cpan
VER=			0.100191
DISTNAME=		WWW-Curl-Simple-${VER}
PKGNAME=		p5-${DISTNAME}
CATEGORIES=		devel perl5
CPAN_AUTHOR=		ANDREMAR

MAINTAINER=		Todd T. Fries <todd@fries.net>

# Artistic
PERMIT_PACKAGE=		Yes
PERMIT_DISTFILES=	Yes

#RUN_DEPENDS+= ${BUILD_DEPENDS}
#BUILD_DEPENDS+= 

CONFIGURE_STYLE= perl

.include <bsd.port.mk>
