# $OpenBSD$

COMMENT =	KDE KPart for viewing SVG
DISTNAME =	svgpart-${MODKDE_VERSION}
CATEGORIES =	graphics

WANTLIB =  c m stdc++
WANTLIB += lib/qt4/QtDBus lib/qt4/QtGui lib/qt4/QtNetwork
WANTLIB += lib/qt4/QtSvg lib/qt4/QtXml
WANTLIB += kdeui kio kparts nepomuk nepomukutils
WANTLIB += soprano

.include <bsd.port.mk>
