# $OpenBSD$

COMMENT =		add test failures if warnings are caught

DISTNAME =		Test-FailWarnings-0.008
CATEGORIES =		devel

MODULES =		cpan
PKG_ARCH =		*

# perl
PERMIT_PACKAGE_CDROM =	Yes

TEST_DEPENDS =		sysutils/p5-Capture-Tiny

.include <bsd.port.mk>
