# $OpenBSD:$

COMMENT =	Determine the locale encoding

DISTNAME =	Encode-Locale-1.03
CATEGORIES =	textproc
CPAN_AUTHOR =	GAAS

MAINTAINER =	Nigel Taylor <nigel@openbsd.org>

# Perl
PERMIT_PACKAGE_CDROM =	Yes
PERMIT_PACKAGE_FTP =	Yes
PERMIT_DISTFILES_CDROM =Yes
PERMIT_DISTFILES_FTP =	Yes

MODULES =	cpan

.include <bsd.port.mk>
