# $OpenBSD$

COMMENT =	2D space arcade game for KDE
DISTNAME =	kspaceduel-${MODKDE_VERSION}

WANTLIB =  c m pthread stdc++
WANTLIB += lib/qt4/QtDBus lib/qt4/QtGui lib/qt4/QtSvg
WANTLIB += kdeui

MODKDE4_USE =	games

.include <bsd.port.mk>
