# $OpenBSD$

COMMENT =	*DEPRECATED* A reader for Build.PL configuration files

MODULES =	cpan
DISTNAME =	ExtUtils-BuildRC-0.005
CATEGORIES =	devel

MAINTAINER =    Sergey Bronnikov <estetus@gmail.com>

# Perl
PERMIT_PACKAGE_CDROM =	Yes

RUN_DEPENDS =	devel/p5-ExtUtils-Helpers

BUILD_DEPENDS =	${RUN_DEPENDS}

.include <bsd.port.mk>
