# $OpenBSD$

ALL_LANGS =

# List of language packs not being built currently due to missing distfiles.
# Should be reviewed at least on each KDE version update.
#ALL_LANGS +=	as ast fy gu he hi id ka kn mai mk ml ms se sq ta tt ug

# List of language packs having distfiles.
ALL_LANGS +=	ar bg bs ca ca@valencia cs da de el en_GB es et eu fa fi fr
ALL_LANGS +=	ga gl hr hu ia is it ja kk km ko lt lv nb nds nl nn pa pl
ALL_LANGS +=	pt pt_BR ro ru si sk sl sr sv tg th tr uk vi wa zh_CN zh_TW
