# $OpenBSD$

COMMENT =		Python module for decorators, wrappers and monkey patching

MODPY_EGG_VERSION =	1.10.4
DISTNAME =		wrapt-${MODPY_EGG_VERSION}
PKGNAME =		py-${DISTNAME}
CATEGORIES =		devel

HOMEPAGE =		https://github.com/GrahamDumpleton/wrapt
MODPY_PI =		Yes


# BSD
PERMIT_PACKAGE_CDROM =	Yes

MODULES =	lang/python

# Requires tox to test
NO_TEST =	Yes

.include <bsd.port.mk>
