# $OpenBSD$

COMMENT =	prevent leakage of lexical hints

MODULES =	cpan
DISTNAME =	Lexical-SealRequireHints-0.007
CATEGORIES =	devel

MAINTAINER =	Sergey Bronnikov <estetus@gmail.com>

# Perl
PERMIT_PACKAGE_CDROM =	Yes

FAKE_FLAGS =	PREFIX=""

.include <bsd.port.mk>
