COMMENT=		OAuth2 for command line apps using web services

MODULES=		cpan
VER=			0.07
DISTNAME=		OAuth-Cmdline-${VER}
PKGNAME=		p5-${DISTNAME}
CATEGORIES=		devel perl5
CPAN_AUTHOR=		ATOOMIC

MAINTAINER=		Todd T. Fries <todd@fries.net>

# Artistic
PERMIT_PACKAGE=	Yes
PERMIT_DISTFILES=   Yes

#RUN_DEPENDS+= ${BUILD_DEPENDS}
#BUILD_DEPENDS+= 

CONFIGURE_STYLE= perl

.include <bsd.port.mk>
