# $OpenBSD: Makefile,v 1.5 2013/03/11 11:41:32 espie Exp $

COMMENT =		monitor the progress of data through a pipeline

DISTNAME =		pv-1.4.12
CATEGORIES =		sysutils

HOMEPAGE =		http://www.ivarch.com/programs/pv.shtml

# Artistic License 2.0
PERMIT_PACKAGE_CDROM=	Yes

MASTER_SITES =		http://www.ivarch.com/programs/sources/

WANTLIB =		c

CONFIGURE_STYLE =	gnu

.include <bsd.port.mk>
