# $OpenBSD$

COMMENT =	use Math::Pari for Math::BigInt routines

MODULES =	cpan
DISTNAME =	Math-BigInt-Pari-1.17
PKGNAME =	p5-${DISTNAME:S/-perl-/-/}
CATEGORIES =	devel

MAINTAINER =    Sergey Bronnikov <estetus@gmail.com>

# Perl
PERMIT_PACKAGE_CDROM =	Yes

.include <bsd.port.mk>
