# : Makefile,v 1.2 2005/12/01 22:37:28 steven Exp $

COMMENT=		currency converter using WebserviceX.net

MODULES=		cpan
VER=			0.07001
DISTNAME=		Finance-Currency-Convert-WebserviceX-${VER}
PKGNAME=		p5-${DISTNAME}
CATEGORIES=		devel perl5
CPAN_AUTHOR=		CLACO

MAINTAINER=		Todd T. Fries <todd@fries.net>

# Artistic
PERMIT_PACKAGE=	Yes
PERMIT_DISTFILES=   Yes

#RUN_DEPENDS+= ${BUILD_DEPENDS}
#BUILD_DEPENDS+= 

CONFIGURE_STYLE= perl

.include <bsd.port.mk>
