# $OpenBSD$

COMMENT =	K Desktop Environment, alphabet learning application
DISTNAME =	klettres-${MODKDE_VERSION}

WANTLIB =  c m pthread stdc++
WANTLIB += lib/qt4/QtDBus lib/qt4/QtGui lib/qt4/QtSvg lib/qt4/QtXml
WANTLIB += kdeui knewstuff3 phonon_s

.include <bsd.port.mk>
