# $OpenBSD: Makefile,v 1.8 2013/03/11 10:50:19 espie Exp $

COMMENT=		find and use installed modules in a (sub)category

MODULES=		cpan
DISTNAME=		Module-Find-0.11
CATEGORIES=		devel

# Artistic
PERMIT_PACKAGE_CDROM=	Yes

MAKE_ENV=		TEST_POD=Yes

.include <bsd.port.mk>
