# $OpenBSD$

CATEGORIES =		games netrek

HOMEPAGE =		http://www.netrek.org

MAINTAINER =		Pascal Stumpf <Pascal.Stumpf@cubes.de>

PERMIT_PACKAGE_CDROM =  Yes
PERMIT_PACKAGE_FTP =    Yes
PERMIT_DISTFILES_CDROM =Yes
PERMIT_DISTFILES_FTP =  Yes

CONFIGURE_STYLE =	gnu

USE_GMAKE =		Yes

NO_REGRESS =		Yes
