
COMMENT =		Fast JSON parsing and encoding

DISTNAME =		aeson-1.4.0.0
REVISION =              1
CATEGORIES =		devel

# BSD3
PERMIT_PACKAGE_CDROM =	Yes

BUILD_DEPENDS=		devel/hs-attoparsec \
                        devel/hs-scientific \
                        devel/hs-tagged \
                        devel/hs-text \
                        devel/hs-time-locale-compat \
                        devel/hs-uuid-types

MODULES =		lang/ghc

MODGHC_BUILD =		cabal hackage haddock register

MODGHC_PACKAGE_KEY =	4YfeQnv7k7r6sMPsAcoTpk

.include <bsd.port.mk>
