# $OpenBSD$

COMMENT =	memory and pairs game for KDE
DISTNAME =	pairs-${MODKDE_VERSION}

WANTLIB =  c m pthread stdc++
WANTLIB += lib/qt4/QtDBus lib/qt4/QtDeclarative lib/qt4/QtGui lib/qt4/QtNetwork
WANTLIB += lib/qt4/QtOpenGL lib/qt4/QtSvg lib/qt4/QtXml lib/qt4/QtXmlPatterns
WANTLIB += kdeclarative kdeui kio knewstuff3 phonon_s

.include <bsd.port.mk>
