# $OpenBSD$

COMMENT =	compiz option code generator

V =		0.8.8
DISTNAME =	compiz-bcop-${V}

MASTER_SITES =	http://releases.compiz.org/${V}/

BUILD_DEPENDS =	textproc/libxslt
RUN_DEPENDS =	textproc/libxslt

CONFIGURE_STYLE = gnu

.include <bsd.port.mk>
