# $OpenBSD$

COMMENT =	themes, graphics and icons for LXQt

VERSION =	0.13.0

NAME=		lxqt-themes
DISTNAME =	${NAME}-${VERSION}

LIB_DEPENDS +=		x11/lxqt/liblxqt

BUILD_DEPENDS +=	x11/lxqt/build-tools

RUN_DEPENDS +=		x11/gtk+3,-guic

NO_TEST =		Yes

.include <bsd.port.mk>
