# $OpenBSD$

COMMENT =	Term::VT102

MODULES =	cpan
DISTNAME =	Term-VT102-Boundless-0.03
CATEGORIES =	devel

MAINTAINER =	Sergey Bronnikov <estetus@gmail.com>

CPAN_AUTHOR =	NUFFIN

# MIT license or Perl
PERMIT_PACKAGE_CDROM =	Yes

RUN_DEPENDS =	devel/p5-Term-VT102

BUILD_DEPENDS =	${RUN_DEPENDS}

.include <bsd.port.mk>
