# $OpenBSD $

COMMENT=	assert the referential identity of a reference

MODULES=	cpan
DISTNAME=	Test-Identity-0.01
PKGNAME=	p5-${DISTNAME}
CATEGORIES=	devel

MAINTAINER =    Todd T. Fries <todd@OpenBSD.org>

# Perl
PERMIT_PACKAGE_CDROM=	Yes

#RUN_DEPENDS=	

#BUILD_DEPENDS=	${RUN_DEPENDS}

.include <bsd.port.mk>
