
COMMENT =		Alternative prelude with batteries and no dependencies

DISTNAME =		foundation-0.0.20
REVISION =		1
CATEGORIES =		devel

# BSD3
PERMIT_PACKAGE_CDROM =	Yes

MODULES =		lang/ghc

MODGHC_BUILD =		cabal hackage haddock register

MODGHC_PACKAGE_KEY =	HOitMdSXh1H2RFYoixhqVb

BUILD_DEPENDS =		devel/hs-basement

.include <bsd.port.mk>
