# $OpenBSD$

COMMENT =		KDE plugins for QImage supporting extra file formats
DISTNAME =		kimageformats-${VERSION}

WANTLIB =  Half Iex IlmImf IlmThread Imath Qt5Core Qt5Gui Qt5PrintSupport
WANTLIB += Qt5Widgets m

LIB_DEPENDS =		graphics/openexr

TEST_IS_INTERACTIVE =	X11

.include <bsd.port.mk>
