COMMENT=		"libdvdread perl binding"
DISTNAME=		DVD-Read-0.04
PKGNAME=		p5-${DISTNAME}
CATEGORIES=		devel perl5

MAINTAINER=		Todd T. Fries <todd@openbsd.org>

# Artistic
PERMIT_PACKAGE=		Yes

#RUN_DEPENDS+= ${BUILD_DEPENDS}
#BUILD_DEPENDS+= 

SITES=    ${SITE_PERL_CPAN:=../../authors/id/N/NA/NANARDON/}

CONFIGURE_STYLE= perl

.include <bsd.port.mk>
