# $OpenBSD$

COMMENT =	K Desktop Environment
DISTNAME =	kdf-${MODKDE_VERSION}

WANTLIB += lib/qt4/QtDBus lib/qt4/QtGui lib/qt4/QtNetwork lib/qt4/QtSvg
WANTLIB += lib/qt4/QtXml c kdeui kio m pthread stdc++

.include <bsd.port.mk>
