# $OpenBSD$

COMMENT =	manipulate kernel sysctl variables on BSD-like systems

MODULES =	cpan
DISTNAME =	BSD-Sysctl-0.10
PKGNAME =	p5-${DISTNAME:S/-perl-/-/}
CATEGORIES =	devel

MAINTAINER =    Sergey Bronnikov <estetus@gmail.com>

# Perl
PERMIT_PACKAGE_CDROM =	Yes

.include <bsd.port.mk>
