
COMMENT =		Implementation of the XDG Base Directory specification.

DISTNAME =		xdg-basedir-0.2.2
REVISION =		1
CATEGORIES =		devel

# BSD3
PERMIT_PACKAGE_CDROM =	Yes

MODULES =		lang/ghc

MODGHC_BUILD =		cabal hackage haddock register

MODGHC_PACKAGE_KEY =	BE46RTaqUyH5g8QWGCnI0N

BUILD_DEPENDS =		

.include <bsd.port.mk>
