# $OpenBSD $

COMMENT=	TAP Test Harness output delegate for html output

MODULES=	cpan
DISTNAME=	TAP-Formatter-HTML-0.11
PKGNAME=	p5-${DISTNAME:S/-perl-/-/}
CATEGORIES=	devel

MAINTAINER =    Sergey Bronnikov <estetus@gmail.com>

# Perl
PERMIT_PACKAGE_CDROM=	Yes

RUN_DEPENDS=	

BUILD_DEPENDS=	${RUN_DEPENDS}

.include <bsd.port.mk>
