# $OpenBSD$

COMMENT =	K Desktop Environment, learning tool for touch typing
DISTNAME =	ktouch-${MODKDE_VERSION}
REVISION =	0

WANTLIB =  c m pthread stdc++
WANTLIB += lib/qt4/QtDBus lib/qt4/QtGui lib/qt4/QtNetwork
WANTLIB += lib/qt4/QtSvg lib/qt4/QtXml
WANTLIB += kdeui kio phonon

.include <bsd.port.mk>
