# $OpenBSD$

COMMENT =	easily build XS extensions that depend on XS extensions

MODULES =	cpan
DISTNAME =	ExtUtils-Depends-0.306
CATEGORIES =	devel

MAINTAINER =    Sergey Bronnikov <estetus@gmail.com>

# Perl
PERMIT_PACKAGE_CDROM =	Yes

.include <bsd.port.mk>
