# $OpenBSD $

COMMENT=	kwalify schema for data structures

MODULES=	cpan
DISTNAME=	Kwalify-1.22
PKGNAME=	p5-${DISTNAME:S/-perl-/-/}
CATEGORIES=	devel

MAINTAINER =    Sergey Bronnikov <estetus@gmail.com>

# Perl
PERMIT_PACKAGE_CDROM=	Yes

.include <bsd.port.mk>
