MODGO_MODULES =	\
	github.com/!burnt!sushi/toml		 v1.4.0 \
	github.com/creasty/defaults		 v1.8.0 \
	github.com/ergochat/readline		 v0.1.3 \
	github.com/golang/snappy		 v0.0.4 \
	github.com/gomarkdown/markdown		 v0.0.0-20240730141124-034f12af3bf6 \
	github.com/google/go-cmp		 v0.6.0 \
	github.com/gopacket/gopacket		 v1.2.0 \
	github.com/itchyny/timefmt-go		 v0.1.6 \
	github.com/kr/pty			 v1.1.1 \
	github.com/kr/text			 v0.1.0 \
	github.com/mattn/go-isatty		 v0.0.20 \
	github.com/mattn/go-runewidth		 v0.0.15 \
	github.com/mitchellh/copystructure	 v1.2.0 \
	github.com/mitchellh/mapstructure	 v1.5.0 \
	github.com/mitchellh/reflectwalk	 v1.0.2 \
	github.com/niemeyer/pretty		 v0.0.0-20200227124842-a10e7caefd8e \
	github.com/rivo/uniseg			 v0.4.7 \
	github.com/vishvananda/netlink		 v1.1.0 \
	github.com/vishvananda/netns		 v0.0.0-20211101163701-50045581ed74 \
	github.com/wader/gojq			 v0.12.1-0.20240822064856-a7688e3344e7 \
	golang.org/x/crypto			 v0.26.0 \
	golang.org/x/exp			 v0.0.0-20240808152545-0cdaa3abc0fa \
	golang.org/x/mod			 v0.20.0 \
	golang.org/x/net			 v0.28.0 \
	golang.org/x/sync			 v0.8.0 \
	golang.org/x/sys			 v0.23.0 \
	golang.org/x/term			 v0.23.0 \
	golang.org/x/text			 v0.17.0 \
	golang.org/x/tools			 v0.24.0 \
	gopkg.in/check.v1			 v1.0.0-20200227125254-8fa46927fb4f \
	gopkg.in/yaml.v3			 v3.0.1

MODGO_MODFILES =	\
	github.com/google/go-cmp	 v0.5.4 \
	golang.org/x/mod		 v0.17.0 \
	golang.org/x/net		 v0.17.0 \
	golang.org/x/net		 v0.21.0 \
	golang.org/x/sys		 v0.13.0 \
	golang.org/x/sys		 v0.15.0 \
	golang.org/x/sys		 v0.20.0 \
	golang.org/x/text		 v0.9.0 \
	golang.org/x/tools		 v0.21.1-0.20240508182429-e35e4ccd0d2d \
	gopkg.in/check.v1		 v0.0.0-20161208181325-20d25e280405

