MODGO_MODULES =	\
	github.com/!burnt!sushi/toml		 v1.5.0 \
	github.com/creasty/defaults		 v1.8.0 \
	github.com/ergochat/readline		 v0.1.3 \
	github.com/golang/snappy		 v0.0.4 \
	github.com/gomarkdown/markdown		 v0.0.0-20250207164621-7a1f277a159e \
	github.com/google/go-cmp		 v0.5.4 \
	github.com/gopacket/gopacket		 v1.3.1 \
	github.com/itchyny/timefmt-go		 v0.1.6 \
	github.com/kr/pty			 v1.1.1 \
	github.com/kr/text			 v0.1.0 \
	github.com/mattn/go-isatty		 v0.0.20 \
	github.com/mattn/go-runewidth		 v0.0.15 \
	github.com/mitchellh/copystructure	 v1.2.0 \
	github.com/mitchellh/mapstructure	 v1.5.0 \
	github.com/mitchellh/reflectwalk	 v1.0.2 \
	github.com/niemeyer/pretty		 v0.0.0-20200227124842-a10e7caefd8e \
	github.com/rivo/uniseg			 v0.4.7 \
	github.com/vishvananda/netlink		 v1.1.0 \
	github.com/vishvananda/netns		 v0.0.0-20211101163701-50045581ed74 \
	github.com/wader/gojq			 v0.12.1-0.20250208151254-0aa7b87b2c2b \
	golang.org/x/crypto			 v0.37.0 \
	golang.org/x/mod			 v0.17.0 \
	golang.org/x/net			 v0.39.0 \
	golang.org/x/sync			 v0.13.0 \
	golang.org/x/sys			 v0.32.0 \
	golang.org/x/term			 v0.31.0 \
	golang.org/x/text			 v0.24.0 \
	golang.org/x/tools			 v0.21.1-0.20240508182429-e35e4ccd0d2d \
	gopkg.in/check.v1			 v1.0.0-20200227125254-8fa46927fb4f \
	gopkg.in/yaml.v3			 v3.0.1

MODGO_MODFILES =	\
	golang.org/x/net	 v0.21.0 \
	golang.org/x/net	 v0.28.0 \
	golang.org/x/sys	 v0.15.0 \
	golang.org/x/sys	 v0.20.0 \
	golang.org/x/sys	 v0.24.0 \
	golang.org/x/text	 v0.9.0 \
	gopkg.in/check.v1	 v0.0.0-20161208181325-20d25e280405

