# $OpenBSD$

COMMENT =	digital camera support for KDE
DISTNAME =	kamera-${MODKDE_VERSION}

WANTLIB =  Qt3Support QtDBus QtGui QtNetwork QtSvg QtXml c gphoto2
WANTLIB += gphoto2_port kdeui kio m stdc++

LIB_DEPENDS = 	graphics/libgphoto2

.include <bsd.port.mk>
