
COMMENT =		Fast, high quality pseudo random number generation

DISTNAME =		mwc-random-0.14.0.0
REVISION =		1
CATEGORIES =		devel

# BSD3
PERMIT_PACKAGE_CDROM =	Yes

MODULES =		lang/ghc

MODGHC_BUILD =		cabal hackage haddock register

MODGHC_PACKAGE_KEY =	9o41LGJzyCgJ0lCiyfjmbk

BUILD_DEPENDS =		devel/hs-math-functions>=0.2.1.0 \
			devel/hs-primitive>=0.6 \
			devel/hs-vector>=0.7

.include <bsd.port.mk>
