# $OpenBSD$

ONLY_FOR_ARCHS = 	i386 amd64

CATEGORIES = 	games games/megaglest

HOMEPAGE = 	http://megaglest.org

MAINTAINER = 	Kirill Bychkov <yason@linklevel.net>

MASTER_SITES = 	${MASTER_SITE_SOURCEFORGE:=megaglest/}
