MODGO_MODULES =	\
	github.com/bitfield/gotestdox	 v0.2.2 \
	github.com/dnephin/pflag	 v1.0.7 \
	github.com/fatih/color		 v1.17.0 \
	github.com/fsnotify/fsnotify	 v1.8.0 \
	github.com/google/go-cmp	 v0.6.0 \
	github.com/google/shlex		 v0.0.0-20191202100458-e7afc7fbc510 \
	github.com/mattn/go-colorable	 v0.1.13 \
	github.com/mattn/go-isatty	 v0.0.20 \
	github.com/rogpeppe/go-internal	 v1.11.0 \
	github.com/yuin/goldmark	 v1.4.13 \
	golang.org/x/mod		 v0.20.0 \
	golang.org/x/net		 v0.28.0 \
	golang.org/x/sync		 v0.8.0 \
	golang.org/x/sys		 v0.30.0 \
	golang.org/x/telemetry		 v0.0.0-20240521205824-bda55230c457 \
	golang.org/x/term		 v0.29.0 \
	golang.org/x/text		 v0.17.0 \
	golang.org/x/tools		 v0.24.0 \
	gotest.tools/v3			 v3.5.1

MODGO_MODFILES =	\
	github.com/fatih/color		 v1.15.0 \
	github.com/google/go-cmp	 v0.5.9 \
	github.com/mattn/go-isatty	 v0.0.16 \
	github.com/mattn/go-isatty	 v0.0.19 \
	golang.org/x/mod		 v0.17.0 \
	golang.org/x/mod		 v0.6.0 \
	golang.org/x/sys		 v0.0.0-20220811171246-fbc7d0a398ab \
	golang.org/x/sys		 v0.1.0 \
	golang.org/x/sys		 v0.10.0 \
	golang.org/x/sys		 v0.13.0 \
	golang.org/x/sys		 v0.18.0 \
	golang.org/x/sys		 v0.23.0 \
	golang.org/x/sys		 v0.6.0 \
	golang.org/x/text		 v0.11.0 \
	golang.org/x/tools		 v0.11.0 \
	golang.org/x/tools		 v0.13.0 \
	golang.org/x/tools		 v0.2.0 \
	golang.org/x/tools		 v0.21.1-0.20240508182429-e35e4ccd0d2d

