# $OpenBSD$

COMMENT =	Perl extension to provide the stuff missing in Hash::Util

MODULES =	cpan
DISTNAME =	Hash-MoreUtils-0.05
CATEGORIES =	devel

MAINTAINER =	Sergey Bronnikov <estetus@gmail.com>

# GNU General Public License or Artistic License
PERMIT_PACKAGE_CDROM =	Yes

RUN_DEPENDS =	devel/p5-Module-Build

BUILD_DEPENDS =	${RUN_DEPENDS}

CONFIGURE_STYLE = modbuild

.include <bsd.port.mk>
