# $OpenBSD $

COMMENT =		piglit is an OpenGL test suite
V=				1
DISTNAME =		piglit-v${V}

EXTRACT_SUFX = 	.tar.gz

CATEGORIES =		devel sysutils
HOMEPAGE =			http://people.freedesktop.org/~nh/piglit/

MAINTAINER =		Sergey Bronnikov <estetus@gmail.com>

PERMIT_PACKAGE_CDROM =	Yes

MASTER_SITES            = ${HOMEPAGE}/snapshot/

WANTLIB += c m stdc++

USE_GMAKE =  			Yes

.include <bsd.port.mk>
