MODGO_MODULES =	\
	github.com/fatih/color		 v1.15.0 \
	github.com/google/go-cmp	 v0.5.9 \
	github.com/mattn/go-colorable	 v0.1.13 \
	github.com/mattn/go-isatty	 v0.0.19 \
	github.com/mattn/go-runewidth	 v0.0.15 \
	github.com/rivo/uniseg		 v0.4.4 \
	github.com/robfig/cron/v3	 v3.0.1 \
	github.com/yuin/goldmark	 v1.5.6 \
	golang.org/x/sync		 v0.3.0 \
	golang.org/x/sys		 v0.12.0 \
	gopkg.in/check.v1		 v0.0.0-20161208181325-20d25e280405 \
	gopkg.in/yaml.v3		 v3.0.1

MODGO_MODFILES =	\
	github.com/mattn/go-isatty	 v0.0.16 \
	github.com/mattn/go-isatty	 v0.0.17 \
	github.com/rivo/uniseg		 v0.2.0 \
	golang.org/x/sys		 v0.0.0-20220811171246-fbc7d0a398ab \
	golang.org/x/sys		 v0.6.0

