MODGO_MODULES =	\
	github.com/bmatcuk/doublestar/v4	 v4.7.1 \
	github.com/fatih/color			 v1.18.0 \
	github.com/google/go-cmp		 v0.6.0 \
	github.com/mattn/go-colorable		 v0.1.13 \
	github.com/mattn/go-isatty		 v0.0.20 \
	github.com/mattn/go-runewidth		 v0.0.16 \
	github.com/mattn/go-shellwords		 v1.0.12 \
	github.com/rivo/uniseg			 v0.4.7 \
	github.com/robfig/cron/v3		 v3.0.1 \
	github.com/yuin/goldmark		 v1.7.8 \
	golang.org/x/sync			 v0.10.0 \
	golang.org/x/sys			 v0.29.0 \
	gopkg.in/check.v1			 v0.0.0-20161208181325-20d25e280405 \
	gopkg.in/yaml.v3			 v3.0.1

MODGO_MODFILES =	\
	github.com/mattn/go-isatty	 v0.0.16 \
	github.com/rivo/uniseg		 v0.2.0 \
	golang.org/x/sys		 v0.0.0-20220811171246-fbc7d0a398ab \
	golang.org/x/sys		 v0.25.0 \
	golang.org/x/sys		 v0.6.0

