# $OpenBSD $

COMMENT=	provides Moose-like method modifiers

MODULES=	cpan
DISTNAME=	Class-Method-Modifiers-2.09
PKGNAME=	p5-${DISTNAME:S/-perl-/-/}
CATEGORIES=	devel

MAINTAINER =    Sergey Bronnikov <estetus@gmail.com>

# Perl
PERMIT_PACKAGE_CDROM=	Yes

RUN_DEPENDS=	

BUILD_DEPENDS=	${RUN_DEPENDS}

.include <bsd.port.mk>
