# $OpenBSD$

COMMENT =	faster conversions to/from Bencode format

MODULES =	cpan
DISTNAME =	Convert-Bencode_XS-0.06
CATEGORIES =	devel

MAINTAINER =	Sergey Bronnikov <estetus@gmail.com>

# Perl
PERMIT_PACKAGE_CDROM =	Yes

.include <bsd.port.mk>
