# $OpenBSD$

COMMENT =		foo something
DISTNAME =		ksysguard-${VERSION}

#SHARED_LIBS =		KF5Foo		0.0

WANTLIB =		

LIB_DEPENDS =		x11/plasma/libksysguard

CONFIGURE_ARGS =	CMAKE_DISABLE_FIND_PACKAGE_Sensors=Yes

.include <bsd.port.mk>
