# $OpenBSD$

COMMENT =	DB-IP IP to City Lite: IPv4/v6 address to city

DISTNAME =	dbip-city-lite-2020-03.mmdb
PKGNAME =	dbip-city-lite-20200301

post-extract:
	mv ${WRKSRC}/${DISTNAME} ${WRKSRC}/dbip-city-lite.mmdb

.include <bsd.port.mk>
