
COMMENT =		Derive Template Haskell Lift class for datatypes

DISTNAME =		th-lift-0.7.10
REVISION =              1
CATEGORIES =		devel

# BSD3
PERMIT_PACKAGE_CDROM =	Yes

BUILD_DEPENDS=		devel/hs-th-abstraction

MODULES =		lang/ghc

MODGHC_BUILD =		cabal hackage haddock register

MODGHC_PACKAGE_KEY =	BH3gL2rcT4FV2x8taNJ5

.include <bsd.port.mk>
