COMMENT=		Accessing Twilio's REST API

MODULES=		cpan
VER=			0.21
DISTNAME=		WWW-Twilio-API-${VER}
PKGNAME=		p5-${DISTNAME}
CATEGORIES=		devel perl5
CPAN_AUTHOR=		SCOTTW

MAINTAINER=		Todd T. Fries <todd@fries.net>

# Artistic
PERMIT_PACKAGE=	Yes
PERMIT_DISTFILES=   Yes

#RUN_DEPENDS+= ${BUILD_DEPENDS}
#BUILD_DEPENDS+= 

CONFIGURE_STYLE= perl

.include <bsd.port.mk>
