# : Makefile,v 1.2 2005/12/01 22:37:28 steven Exp $

COMMENT=		Minimaist Fennec, the commonly used bits.

MODULES=		cpan
VER=			0.004
DISTNAME=		Fennec-Lite-${VER}
PKGNAME=		p5-${DISTNAME}
CATEGORIES=		devel perl5
CPAN_AUTHOR=		EXODIST

MAINTAINER=		Todd T. Fries <todd@fries.net>

# Artistic
PERMIT_PACKAGE=	Yes
PERMIT_DISTFILES=   Yes

#RUN_DEPENDS+= ${BUILD_DEPENDS}
#BUILD_DEPENDS+= 

CONFIGURE_STYLE= perl modbuild

.include <bsd.port.mk>
