
COMMENT =		Type class for sequence of bytes

DISTNAME =		byteable-0.1.1
REVISION =		1
CATEGORIES =		devel

# BSD3
PERMIT_PACKAGE_CDROM =	Yes

MODULES =		lang/ghc

MODGHC_BUILD =		cabal hackage haddock register

MODGHC_PACKAGE_KEY =	4PLPgH6a2E14oN7yL5y3oL

BUILD_DEPENDS =		

.include <bsd.port.mk>
