# $OpenBSD$

    SUBDIR += libraries
    SUBDIR += scanner
    SUBDIR += client
    SUBDIR += cli
    SUBDIR += manager
    SUBDIR += administrator
    SUBDIR += gsa
    SUBDIR += gsd

.include <bsd.port.subdir.mk>
