# : Makefile,v 1.2 2005/12/01 22:37:28 steven Exp $

COMMENT=		Easy, versatile, portable file handling

MODULES=		cpan
VER=			4.201720
DISTNAME=		File-Util-${VER}
PKGNAME=		p5-${DISTNAME}
CATEGORIES=		devel perl5
CPAN_AUTHOR=		TOMMY

MAINTAINER=		Todd T. Fries <todd@fries.net>

# Artistic
PERMIT_PACKAGE=	Yes
PERMIT_DISTFILES=   Yes

#RUN_DEPENDS+= ${BUILD_DEPENDS}
#BUILD_DEPENDS+= 

CONFIGURE_STYLE= perl

.include <bsd.port.mk>
