# $OpenBSD$

COMMENT =	replacement for if ($foo eq 'bar')

MODULES =	cpan
DISTNAME =	Object-Enum-0.072
CATEGORIES =	devel

MAINTAINER =	Sergey Bronnikov <estetus@gmail.com>

# Perl
PERMIT_PACKAGE_CDROM =	Yes

RUN_DEPENDS =	devel/p5-Sub-Install \
		devel/p5-Sub-Exporter \
		devel/p5-Test-Simple \
		devel/p5-Class-Data-Inheritable \
		devel/p5-Class-Accessor-Fast

BUILD_DEPENDS =	${RUN_DEPENDS}

.include <bsd.port.mk>
