
COMMENT =		Integer library based on GMP

DISTNAME =		integer-gmp-1.0.2.0
REVISION =		1
CATEGORIES =		devel

# BSD3
PERMIT_PACKAGE_CDROM =	Yes

MODULES =		lang/ghc

MODGHC_BUILD =		cabal hackage haddock register

MODGHC_PACKAGE_KEY =	9o41LGJzyCgJ0lCiyfjmbk

BUILD_DEPENDS =		

.include <bsd.port.mk>
