
COMMENT =		Haskell implementation of a javascript minifier

DISTNAME =		hjsmin-0.2.0.2
REVISION =		1
CATEGORIES =		devel

# BSD3
PERMIT_PACKAGE_CDROM =	Yes

MODULES =		lang/ghc

MODGHC_BUILD =		cabal hackage haddock register

MODGHC_PACKAGE_KEY =	9EFfOoA1Ky0Fgn1Bnwg4Gh

BUILD_DEPENDS =		devel/hs-blaze-builder>=0.2 \
			devel/hs-language-javascript \
			devel/hs-optparse-applicative>=0.7 \
			devel/hs-text>=0.8

.include <bsd.port.mk>
