# $OpenBSD$

COMMENT =		SHA message digests

DISTNAME =		SHA-1.6.4.2

CATEGORIES =		security

HOMEPAGE =		https://hackage.haskell.org/package/SHA

MAINTAINER =		Pascal Stumpf <Pascal.Stumpf@cubes.de>

# BSD3
PERMIT_PACKAGE_CDROM =	Yes

MODULES =		lang/ghc

MODGHC_BUILD =		cabal hackage haddock register

MODGHC_PACKAGE_KEY =	0ooW8jYoKWjDUFkZlEvhJX

.include <bsd.port.mk>
