# $OpenBSD $

COMMENT=	centralized test suite for Sys::Info

MODULES=	cpan
DISTNAME=	Test-Sys-Info-0.20
PKGNAME=	p5-${DISTNAME:S/-perl-/-/}
CATEGORIES=	www

MAINTAINER =    Sergey Bronnikov <estetus@gmail.com>

# Perl
PERMIT_PACKAGE_CDROM=	Yes

.include <bsd.port.mk>
