# $OpenBSD$

COMMENT =	KDE mobipocket plugins for Strigi, Okular and thumbnails
DISTNAME =	kdegraphics-mobipocket-${MODKDE_VERSION}

LIB_DEPENDS =	databases/strigi \
		x11/kde4/okular

.include <bsd.port.mk>
