# $OpenBSD $

COMMENT=	represent an operation awaiting completion

MODULES=	cpan
CPAN_AUTHOR=	PEVANS
DISTNAME=	Future-0.23
PKGNAME=	p5-${DISTNAME}
CATEGORIES=	devel

MAINTAINER =    Todd T. Fries <todd@OpenBSD.org>

# Perl
PERMIT_PACKAGE_CDROM=	Yes

#RUN_DEPENDS=	

#BUILD_DEPENDS=	${RUN_DEPENDS}

.include <bsd.port.mk>
