# $OpenBSD$

COMMENT=	sieve support for PHP

DISTNAME=	Net_Sieve-1.3.2
CATEGORIES=	net

MODULES=	www/pear

# BSD License
PERMIT_PACKAGE_CDROM=	Yes

RUN_DEPENDS=	net/pear-Net-Socket \
		security/pear-Auth-SASL

.include <bsd.port.mk>
