# $OpenBSD$

COMMENT =		library to enable your code run as a daemon process

MODPY_EGG_VERSION =	2.4.7
DISTNAME =		daemonize-${MODPY_EGG_VERSION}
PKGNAME =		py-daemonize-${MODPY_EGG_VERSION}

CATEGORIES =		sysutils

HOMEPAGE =		https://github.com/thesharp/daemonize

MAINTAINER =		XXX XXX <xxx@xxx.xxx>

# MIT
PERMIT_PACKAGE_CDROM =	Yes

MODULES =		lang/python
MODPY_SETUPTOOLS =	Yes
MODPY_PI =		Yes

FLAVORS=python3
FLAVOR?=


.include <bsd.port.mk>
