# $OpenBSD$

COMMENT =		schema and data migrations for Django projects

DISTNAME =		South-0.8.4
PKGNAME =		py-south-0.8.4

CATEGORIES =		devel

HOMEPAGE =		http://south.aeracode.org

MAINTAINER =		Sergey Bronnikov <estetus@gmail.com>	

# Apache Software License
PERMIT_PACKAGE_CDROM =	Yes

MASTER_SITES =		${MASTER_SITE_PYPI:=S/South/}

MODULES =		lang/python

NO_BUILD =		Yes
#NO_TEST =		Yes

.include <bsd.port.mk>
