# $OpenBSD$

COMMENT=	random password generator based on FIPS-181

MODULES=	cpan
DISTNAME=	Crypt-RandPasswd-0.02
CATEGORIES=	security
MAINTAINER=	Andrew Fresh <andrew@afresh1.com>

# Artistic 2.0
PERMIT_PACKAGE_CDROM=	Yes

.include <bsd.port.mk>
