# : Makefile,v 1.2 2005/12/01 22:37:28 steven Exp $

COMMENT=		module for posting messages to Discord chat service

MODULES=		cpan
VER=			1.10
DISTNAME=		WebService-Discord-Webhook-${VER}
PKGNAME=		p5-${DISTNAME}
CATEGORIES=		www perl5
CPAN_AUTHOR=		GREGK

MAINTAINER=		Todd T. Fries <todd@fries.net>

# Artistic
PERMIT_PACKAGE=	Yes
PERMIT_DISTFILES=   Yes

#RUN_DEPENDS+= ${BUILD_DEPENDS}
#BUILD_DEPENDS+= 

CONFIGURE_STYLE= perl

.include <bsd.port.mk>
