
COMMENT =		Implementation of bounded channels.

DISTNAME =		BoundedChan-1.0.3.0
REVISION =		1
CATEGORIES =		devel

# BSD3
PERMIT_PACKAGE_CDROM =	Yes

MODULES =		lang/ghc

MODGHC_BUILD =		cabal hackage haddock register

MODGHC_PACKAGE_KEY =	J4PM0Sd66IX3gUNt3QPx5O

BUILD_DEPENDS =		

.include <bsd.port.mk>
