# $OpenBSD$

COMMENT= 	Perl extension for accessing the Trango telnet interface

DISTNAME=	Net-Telnet-Trango-0.05
CATEGORIES=	net

MAINTAINER=	Andrew Fresh <andrew@cpan.org>

PERMIT_PACKAGE_CDROM=   Yes

MODULES=	cpan

RUN_DEPENDS=	net/p5-Net-Telnet

.include <bsd.port.mk>
