# $OpenBSD: Makefile.template,v 1.91 2021/11/09 13:43:15 kn Exp $

COMMENT =	C++ functions analgous to python string methods

GH_ACCOUNT =	imageworks
GH_PROJECT =	pystring
GH_TAGNAME =	v1.1.3

SHARED_LIBS +=  pystring                  0.0 # 0.0

CATEGORIES =	devel

MAINTAINER =	Dimitri Karamazov <deserter666@danwin1210.me>

# BSD
PERMIT_PACKAGE =Yes

MAKE_ENV =	CXX=${CXX}

USE_GMAKE =	Yes

.include <bsd.port.mk>
