# $OpenBSD$

COMMENT =	Perl extension for 32 bit Jenkins Hashing Algorithm

MODULES =	cpan
DISTNAME =	Digest-JHash-0.07
CATEGORIES =	security

MAINTAINER =	Sergey Bronnikov <estetus@gmail.com>

# Artistic License 2.0
PERMIT_PACKAGE_CDROM =	Yes

.include <bsd.port.mk>
