COMMENT =	language server for Perl

DISTNAME =	Perl-LanguageServer-2.6.2
PKGNAME =	${DISTNAME:L}

CATEGORIES =	devel

# Artistic 2.0
PERMIT_PACKAGE=	Yes

RUN_DEPENDS +=	devel/p5-AnyEvent devel/p5-Coro devel/p5-Moose \
		converters/p5-JSON devel/p5-IO-AIO devel/p5-AnyEvent-AIO \
		devel/p5-Data-Dump devel/p5-PadWalker textproc/p5-Encode-Locale \
		devel/p5-Scalar-List-Utils devel/p5-Class-Refresh \
		devel/p5-Compiler-Lexer devel/p5-Hash-SafeKeys \
		textproc/p5-Encode-Locale

MODULES =	cpan

.include <bsd.port.mk>
