# $OpenBSD$

COMMENT =	manipulate 64 bits integers in Perl

DISTNAME =	Math-Int64-0.54

CATEGORIES =	math

MAINTAINER =	Frederic Cambus <fcambus@openbsd.org>

# Perl
PERMIT_PACKAGE_CDROM =	Yes

WANTLIB +=	c perl

MODULES =	cpan

.include <bsd.port.mk>
