
COMMENT =		shell-like (systems) programming in Haskell

DISTNAME =		shelly-1.8.1
REVISION =		1
CATEGORIES =		devel

# BSD3
PERMIT_PACKAGE_CDROM =	Yes

MODULES =		lang/ghc

MODGHC_BUILD =		cabal hackage haddock register

MODGHC_PACKAGE_KEY =	AniTQIm5IUwIP5xMmmB1Qm

BUILD_DEPENDS =		devel/hs-async \
			devel/hs-enclosed-exceptions \
			devel/hs-exceptions>=0.6 \
			devel/hs-lifted-async \
			devel/hs-lifted-base \
			devel/hs-monad-control>=0.3.2,<1.1 \
			devel/hs-mtl>=2 \
			devel/hs-system-fileio<0.4 \
			devel/hs-system-filepath>=0.4.7,<0.5 \
			devel/hs-text \
			devel/hs-transformers-base \
			devel/hs-unix-compat<0.6

.include <bsd.port.mk>
