# $OpenBSD$

     SUBDIR =
     SUBDIR += caja
     SUBDIR += control-center
     SUBDIR += desktop
     SUBDIR += icon-theme
     SUBDIR += libmatekbd
     SUBDIR += libmatemixer
     SUBDIR += libmateweather
     SUBDIR += marco
     SUBDIR += menus
     SUBDIR += panel
     SUBDIR += power-manager
     SUBDIR += screensaver
     SUBDIR += session-manager
     SUBDIR += settings-daemon
     SUBDIR += terminal
     SUBDIR += themes

.include <bsd.port.subdir.mk>
