# $OpenBSD$

COMMENT =		efficient SMT solver library (angr fork)

ANGR_PYTHON_MODULE =	z3-solver
MODPY_EGG_VERSION =	4.5.1.0.post2

CATEGORIES +=		math

HOMEPAGE =		https://github.com/angr/angr-z3

WANTLIB += 		${COMPILER_LIBCXX} c m

FLAVORS =		python3
FLAVOR ?=

.include <bsd.port.mk>
