
COMMENT =		compatibility layer for base

DISTNAME =		base-compat-0.10.4
REVISION =              1
CATEGORIES =		devel

# BSD3
PERMIT_PACKAGE_CDROM =	Yes

MODULES =		lang/ghc

MODGHC_BUILD =		cabal hackage haddock register

MODGHC_PACKAGE_KEY =	HHFC7n3Zk9W39R5xSFJI

.include <bsd.port.mk>
