.\"     $OpenBSD: clion.1,v 1.1 2018/05/27 17:09:44 rsadowski Exp $
.Dd $Mdocdate: May 27 2018 $
.Dt CLION 1
.Os
.Sh NAME
.Nm clion
.Nd launch CLion C and C++ Development Environment
.Sh SYNOPSIS
.Nm
.Op jvm-args
.Sh DESCRIPTION
.Nm
starts up the JetBrains CLion C and C++ Development Environment
.Sh SEE ALSO
The web site
.Lk https://www.jetbrains.com/clion/ .
