# $OpenBSD$

COMMENT =	KDE strigi analyzer for graphics files
DISTNAME =	kdegraphics-strigi-analyzer-${MODKDE_VERSION}
REVISION =	0

WANTLIB =  c m stdc++
WANTLIB += streamanalyzer streams tiff

MODKDE4_NO_QT =	Yes
MODKDE4_USE =

BUILD_DEPENDS =	x11/kde4/libs

LIB_DEPENDS =	databases/strigi

.include <bsd.port.mk>
