# $OpenBSD$

COMMENT =	centralized test suite for Sys::Info

MODULES =	cpan
DISTNAME =	Test-Sys-Info-0.20
PKGNAME =	p5-${DISTNAME:S/-perl-/-/}
CATEGORIES =	devel

MAINTAINER =    Sergey Bronnikov <estetus@gmail.com>

# Perl
PERMIT_PACKAGE_CDROM =	Yes

TEST_DEPENDS = 	devel/p5-Test-Pod \
		devel/p5-Test-Pod-Coverage

.include <bsd.port.mk>
