# $OpenBSD$

COMMENT =		removes body for HTTP response if it's not required

MODULES =		cpan
DISTNAME =		Plack-Middleware-RemoveRedundantBody-0.05
CATEGORIES =		www

MAINTAINER =		Cesare Gargano <gar@plusiagamma.org>

BUILD_DEPENDS =		${RUN_DEPENDS}

RUN_DEPENDS =		www/p5-Plack

# Perl
PERMIT_PACKAGE_CDROM =	Yes

.include <bsd.port.mk>
