# $OpenBSD$

COMMENT =		foo something
DISTNAME =		polkit-kde-agent-1-${VERSION}
PKGNAME =		polkit-kde-agent_1-${VERSION}

#SHARED_LIBS =		KF5Foo		0.0

WANTLIB =		

#LIB_DEPENDS =		foo/bar

.include <bsd.port.mk>
