# $OpenBSD$

COMMENT =	base class for Sys::Info

MODULES =	cpan
DISTNAME =	Sys-Info-Base-0.7803
CATEGORIES =	devel

MAINTAINER =	Sergey Bronnikov <estetus@gmail.com>

# Perl
PERMIT_PACKAGE_CDROM =	Yes

.include <bsd.port.mk>
