# $OpenBSD: Makefile,v 1.2 2016/12/25 14:54:48 zhuk Exp $

COMMENT =	KDE Breeze-style light and dark icon themes
DISTNAME =	breeze-icons-${VERSION}

WANTLIB- =

RUN_DEPENDS =	x11/gtk+3,-guic

PKG_ARCH =	*

.include <bsd.port.mk>
