
COMMENT =		Efficient algorithms for vector arrays

DISTNAME =		vector-algorithms-0.7.0.1
REVISION =		1
CATEGORIES =		devel

# BSD3
PERMIT_PACKAGE_CDROM =	Yes

MODULES =		lang/ghc

MODGHC_BUILD =		cabal hackage haddock register

MODGHC_PACKAGE_KEY =	8fm7xs5iHII7qJo7r5ggbe

BUILD_DEPENDS =		devel/hs-mtl \
			devel/hs-mwc-random \
			devel/hs-primitive>=0.3,<0.7 \
			devel/hs-vector>=0.6,<0.13

.include <bsd.port.mk>
