# $OpenBSD$

MODPY_EGG_VERSION =	0.3.72
COMMENT =	download YouTube content and retrieve metadata
DISTNAME =	Pafy-${MODPY_EGG_VERSION}
PKGNAME =	py-pafy-${MODPY_EGG_VERSION}
CATEGORIES =	net

HOMEPAGE =	http://pythonhosted.org/Pafy/
MAINTAINER =	Brian Callahan <bcallah@openbsd.org>

# LGPLv3+
PERMIT_PACKAGE_CDROM =	Yes

MASTER_SITES =	${MASTER_SITE_PYPI:=p/pafy/}

MODULES =	lang/python
MODPY_SETUPTOOLS =	Yes

.include <bsd.port.mk>
