COMMENT=		"treat hashes as objects, with arbitrary accessors/mutators"
DISTNAME=		Hash-AsObject-0.13
PKGNAME=		p5-${DISTNAME}
CATEGORIES=		devel perl5

MAINTAINER=		Todd T. Fries <todd@openbsd.org>

# Artistic
PERMIT_PACKAGE=	Yes

#RUN_DEPENDS+= ${BUILD_DEPENDS}
#BUILD_DEPENDS+= 

MASTER_SITES=    ${MASTER_SITE_PERL_CPAN:=../../authors/id/N/NK/NKUITSE/}

CONFIGURE_STYLE= perl

.include <bsd.port.mk>
