# $OpenBSD$

VERSION =		5.4.3
COMMENT =		Oxygen style fonts for KDE 5
DISTNAME =		oxygen-fonts-${VERSION}

WANTLIB- =
LIB_DEPENDS- =

BUILD_DEPENDS =		print/fontforge

CONFIGURE_ARGS =	-DOXYGEN_FONT_INSTALL_DIR=${PREFIX}/share/fonts/oxygen

.include <bsd.port.mk>
