# $OpenBSD$

COMMENT =		decompressor written in C for lzip files

V =			1.3
DISTNAME =		lunzip-${V}

HOMEPAGE =		http://lzip.nongnu.org/lunzip.html

# GPLv3+
PERMIT_PACKAGE_CDROM =	Yes

WANTLIB =		c

.include <bsd.port.mk>
