
COMMENT =		Commonly useful parser combinators

DISTNAME =		parser-combinators-0.4.0
REVISION =              2
CATEGORIES =		devel

# BSD3
PERMIT_PACKAGE_CDROM =	Yes

MODULES =		lang/ghc

MODGHC_BUILD =		cabal hackage haddock register

MODGHC_PACKAGE_KEY =	7gtgQtRzF8dJxVKU85PTIR

.include <bsd.port.mk>
