# $OpenBSD$

COMMENT =	recursively merge two or more hashes, simply

MODULES =	cpan
DISTNAME =	Hash-Merge-Simple-0.051
CATEGORIES =	devel

MAINTAINER =	Sergey Bronnikov <estetus@gmail.com>

# Perl
PERMIT_PACKAGE_CDROM =	Yes

RUN_DEPENDS =	devel/p5-Clone

TEST_DEPENDS =	devel/p5-Test-Deep \
		devel/p5-Test-Most

.include <bsd.port.mk>
