
COMMENT =		memory and related abstraction stuff

DISTNAME =		memory-0.14.16
REVISION =		1
CATEGORIES =		devel

# BSD3
PERMIT_PACKAGE_CDROM =	Yes

MODULES =		lang/ghc

MODGHC_BUILD =		cabal hackage haddock register

MODGHC_PACKAGE_KEY =	90ZvZkwyKaT183ULDNL3KX

BUILD_DEPENDS =		devel/hs-foundation>=0.0.8

.include <bsd.port.mk>
