# $OpenBSD$

COMMENT =	K Desktop Environment, character select and clipboard copy
DISTNAME =	kcharselect-${MODKDE_VERSION}

WANTLIB =  c m pthread stdc++
WANTLIB += lib/qt4/QtDBus lib/qt4/QtGui lib/qt4/QtSvg
WANTLIB += kdeui

.include <bsd.port.mk>
