# $OpenBSD $

COMMENT=	retrieve BSD platform metadata

MODULES=	cpan
DISTNAME=	Devel-Platform-Info-0.10
PKGNAME=	p5-${DISTNAME:S/-perl-/-/}
CATEGORIES=	devel

MAINTAINER =    Sergey Bronnikov <estetus@gmail.com>

# Perl
PERMIT_PACKAGE_CDROM=	Yes

.include <bsd.port.mk>
