
COMMENT =		Simple cryptographic random related types

DISTNAME =		crypto-random-0.0.9
REVISION =		1
CATEGORIES =		devel

# BSD3
PERMIT_PACKAGE_CDROM =	Yes

MODULES =		lang/ghc

MODGHC_BUILD =		cabal hackage haddock register

MODGHC_PACKAGE_KEY =	1CbZuQUUl1h9uvj3hXk6o2

BUILD_DEPENDS =		devel/hs-securemem \
			devel/hs-vector

.include <bsd.port.mk>
