# $OpenBSD$

COMMENT =	go from cardinal (3) to ordinal (3rd)

DISTNAME =	Lingua-EN-Numbers-Ordinate-1.03
CATEGORIES =	textproc

MAINTAINER =	Nigel Taylor <nigel@openbsd.org>

# Perl
PERMIT_PACKAGE_CDROM =	 Yes

MODULES =	cpan

.include <bsd.port.mk>
