# $OpenBSD: Makefile,v 1.25 2010/06/24 07:45:06 espie Exp $

     SUBDIR =
# don't even try to keep these sorted
# basic bricks
     SUBDIR += automoc
     SUBDIR += attica
     SUBDIR += akonadi
     SUBDIR += oxygen-icons

# libraries

     SUBDIR += libs
     SUBDIR += pimlibs
     SUBDIR += qimageblitz

# extra base
     SUBDIR += kde-runtime
     SUBDIR += kde-workspace
     SUBDIR += kdepim-runtime

# fat packages
     SUBDIR += admin
     SUBDIR += games
     SUBDIR += multimedia
     SUBDIR += network
     SUBDIR += sdk
     SUBDIR += toys
     SUBDIR += utils
     SUBDIR += webdev

# actual apps
     SUBDIR += accessibility
     SUBDIR += edu
     SUBDIR += graphics
     SUBDIR += pim
#     SUBDIR += extragear-plasma

# additional resources
    SUBDIR += artwork
    SUBDIR += kde-wallpapers
    SUBDIR += l10n

.include <bsd.port.subdir.mk>
