# $OpenBSD$

COMMENT =		unpadded Base64

MODPY_EGG_VERSION =	1.1.0
PKGNAME =		py-unpaddedbase64-${MODPY_EGG_VERSION}
GH_ACCOUNT =	matrix-org
GH_PROJECT =	python-unpaddedbase64
GH_TAGNAME =	v${MODPY_EGG_VERSION}

CATEGORIES =		textproc

HOMEPAGE =		None

MAINTAINER =		XXX XXX <xxx@xxx.xxx>

# Apache 2.0
PERMIT_PACKAGE_CDROM =	Yes

MODULES =		lang/python
MODPY_SETUPTOOLS =	Yes
FLAVORS =	python3
FLAVOR?=

.include <bsd.port.mk>
