# $OpenBSD$

COMMENT =	common functions for all Tapper classes

MODULES =	cpan
DISTNAME =	Tapper-Base-4.1.4
CATEGORIES =	www

MAINTAINER =    Sergey Bronnikov <estetus@gmail.com>

# 2-clause BSD
PERMIT_PACKAGE_CDROM =	Yes

RUN_DEPENDS =	devel/p5-common-sense \
		devel/p5-Moose \
		devel/p5-LockFile-Simple \
		devel/p5-Module-Find \
		devel/p5-MooseX-Log-Log4perl

BUILD_DEPENDS =	devel/p5-Log-Log4perl

.include <bsd.port.mk>
