# $OpenBSD$

COMMENT =		C implementation of lzip

V =			1.4
DISTNAME =		clzip-${V}

HOMEPAGE =		http://lzip.nongnu.org/clzip.html

# GPLv3+
PERMIT_PACKAGE_CDROM =	Yes

WANTLIB =		c

.include <bsd.port.mk>
