# Autogenerated! Do not manually edit.

# sam core
sam_CORE_CXX_SRC = \
	arduino-support/sam/cores/arduino/new.cpp \
	arduino-support/sam/cores/arduino/USB/USBCore.cpp \
	arduino-support/sam/cores/arduino/Reset.cpp \
	arduino-support/sam/cores/arduino/WString.cpp \
	arduino-support/sam/cores/arduino/UARTClass.cpp \
	arduino-support/sam/cores/arduino/Print.cpp \
	arduino-support/sam/cores/arduino/abi.cpp \
	arduino-support/sam/cores/arduino/RingBuffer.cpp \
	arduino-support/sam/cores/arduino/WMath.cpp \
	arduino-support/sam/cores/arduino/USB/HID.cpp \
	arduino-support/sam/cores/arduino/wiring_pulse.cpp \
	arduino-support/sam/cores/arduino/USARTClass.cpp \
	arduino-support/sam/cores/arduino/USB/CDC.cpp \
	arduino-support/sam/cores/arduino/Stream.cpp \
	arduino-support/sam/cores/arduino/main.cpp \
	arduino-support/sam/cores/arduino/IPAddress.cpp
sam_CORE_C_SRC = \
	arduino-support/sam/cores/arduino/wiring.c \
	arduino-support/sam/cores/arduino/wiring_digital.c \
	arduino-support/sam/cores/arduino/wiring_analog.c \
	arduino-support/sam/cores/arduino/WInterrupts.c \
	arduino-support/sam/cores/arduino/itoa.c \
	arduino-support/sam/cores/arduino/wiring_shift.c \
	arduino-support/sam/cores/arduino/hooks.c \
	arduino-support/sam/cores/arduino/avr/dtostrf.c \
	arduino-support/sam/cores/arduino/cortex_handlers.c \
	arduino-support/sam/cores/arduino/iar_calls_sam3.c \
	arduino-support/sam/cores/arduino/syscalls_sam3.c
sam_CORE_INC_DIRS = \
	arduino-support/sam/cores/arduino/USB \
	arduino-support/sam/cores/arduino/avr \
	arduino-support/sam/cores/arduino

# avr core
avr_CORE_CXX_SRC = \
	arduino-support/avr/cores/arduino/CDC.cpp \
	arduino-support/avr/cores/arduino/HardwareSerial.cpp \
	arduino-support/avr/cores/arduino/main.cpp \
	arduino-support/avr/cores/arduino/HID.cpp \
	arduino-support/avr/cores/arduino/HardwareSerial2.cpp \
	arduino-support/avr/cores/arduino/new.cpp \
	arduino-support/avr/cores/arduino/IPAddress.cpp \
	arduino-support/avr/cores/arduino/USBCore.cpp \
	arduino-support/avr/cores/arduino/Print.cpp \
	arduino-support/avr/cores/arduino/HardwareSerial3.cpp \
	arduino-support/avr/cores/arduino/Tone.cpp \
	arduino-support/avr/cores/arduino/HardwareSerial0.cpp \
	arduino-support/avr/cores/arduino/Stream.cpp \
	arduino-support/avr/cores/arduino/HardwareSerial1.cpp \
	arduino-support/avr/cores/arduino/WString.cpp \
	arduino-support/avr/cores/arduino/abi.cpp \
	arduino-support/avr/cores/arduino/WMath.cpp
avr_CORE_C_SRC = \
	arduino-support/avr/cores/arduino/WInterrupts.c \
	arduino-support/avr/cores/arduino/hooks.c \
	arduino-support/avr/cores/arduino/wiring.c \
	arduino-support/avr/cores/arduino/wiring_shift.c \
	arduino-support/avr/cores/arduino/wiring_analog.c \
	arduino-support/avr/cores/arduino/wiring_pulse.c \
	arduino-support/avr/cores/arduino/wiring_digital.c
avr_CORE_INC_DIRS = \
	arduino-support/avr/cores/arduino

