# $OpenBSD$
# This file is autogenerated. Do not edit.

tl-symlinks-buildset:
	cd ${PREFIX}/bin && \
		ln -s latex pdftex \
		ln -s etex pdftex \
		ln -s dviluatex luatex \
		ln -s tex tex \
		ln -s pdfetex pdftex \
		ln -s pdflatex pdftex \
		ln -s luajitlatex luajittex \
		ln -s luatex luatex \
		ln -s mf mf-nowin \
		ln -s lualatex luatex \
		ln -s luajittex luajittex \
		ln -s mptopdf pdftex \
		ln -s pdftex pdftex \
		ln -s dvilualatex luatex

tl-symlinks-main:
	cd ${PREFIX}/bin && \
		ln -s mex pdftex \
		ln -s mltex pdftex \
		ln -s xetex xetex \
		ln -s lamed aleph \
		ln -s mllatex pdftex \
		ln -s csplain pdftex \
		ln -s xelatex xetex \
		ln -s pdfmex pdftex \
		ln -s eplain pdftex \
		ln -s aleph aleph \
		ln -s xmltex pdftex \
		ln -s pdfjadetex pdftex \
		ln -s amstex pdftex \
		ln -s texsis pdftex \
		ln -s lollipop tex \
		ln -s jadetex pdftex \
		ln -s pdfcslatex pdftex \
		ln -s utf8mex pdftex \
		ln -s pdfcsplain pdftex \
		ln -s luacsplain luatex \
		ln -s pdfxmltex pdftex \
		ln -s cslatex pdftex

tl-symlinks-full:
	cd ${PREFIX}/bin && \
		ln -s eptex eptex \
		ln -s ptex ptex \
		ln -s euptex euptex \
		ln -s uptex uptex \
		ln -s uplatex euptex \
		ln -s mflua mflua-nowin \
		ln -s platex eptex

tl-symlinks-context:
	true

