# $OpenBSD: Makefile,v 1.5 2017/10/26 07:53:24 rsadowski Exp $

COMMENT =	KDE helper for multithreaded programming
DISTNAME =	threadweaver-${VERSION}

SHARED_LIBS =	KF5ThreadWeaver		4.0

WANTLIB += ${COMPILER_LIBCXX} Qt5Core m

.include <bsd.port.mk>
