
COMMENT =		HTTP cookie parsing and rendering

DISTNAME =		cookie-0.4.4
REVISION =		1
CATEGORIES =		devel

# BSD3
PERMIT_PACKAGE_CDROM =	Yes

MODULES =		lang/ghc

MODGHC_BUILD =		cabal hackage haddock register

MODGHC_PACKAGE_KEY =	1NgbbOfwxjjGo6IX8WM10y

BUILD_DEPENDS =		devel/hs-data-default-class \
			devel/hs-text>=1.1

.include <bsd.port.mk>
