# $OpenBSD$

COMMENT =	plugin-based library to create KDE window decorations
DISTNAME =	kdecoration-${VERSION}

SHARED_LIBS =	kdecorations2		0.0 # 5.5
SHARED_LIBS +=	kdecorations2private	0.0 # 5.5

WANTLIB =	Qt5Core Qt5Gui m

TEST_IS_INTERACTIVE =	X11

.include <bsd.port.mk>
