#!/bin/sh

if [ -f "/usr/local/share/kannel/enabled_kannel_box" ]; then
    . /usr/local/share/kannel/enabled_kannel_box
    if [[ ${WAPBOX_ENABLED} != "yes" ]]; then
	echo "WAPBOX_ENABLED=\"yes\"" >> /usr/local/share/kannel/enabled_kannel_box
	print -n "Kannel WAP box enable ...\n"
    fi
    print -n "Kannel WAP box is enabled ...\n"
else
    mkdir -p /usr/local/share/kannel
    echo "WAPBOX_ENABLED=\"yes\"" >> /usr/local/share/kannel/enabled_kannel_box
    print -n "Kannel WAP box enable ...\n"
fi

exit 0
