# $OpenBSD$

COMMENT =	parse string that represents time duration

MODULES =	cpan
DISTNAME =	Time-Duration-Parse-0.06
CATEGORIES =	devel

MAINTAINER =	Sergey Bronnikov <estetus@gmail.com>

# Perl
PERMIT_PACKAGE_CDROM =	Yes

RUN_DEPENDS =	devel/p5-Exporter-Lite

BUILD_DEPENDS =	${RUN_DEPENDS}

USE_GROFF =	Yes

.include <bsd.port.mk>
