# $OpenBSD$

COMMENT=	Perl interface to Palm Keyrings

DISTNAME=	Palm-Keyring-0.96_07
CATEGORIES=	perl5 misc

MAINTAINER=	Andrew Fresh <andrew@cpan.org>

PERMIT_PACKAGE_CDROM=   Yes

MODULES=	cpan
CPAN_AUTHOR=	ANDREW

RUN_DEPENDS=    databases/p5-Palm

.include <bsd.port.mk>
