MODGO_MODULES =	\
	github.com/davecgh/go-spew	 v1.1.1 \
	github.com/mattn/go-zglob	 v0.0.4 \
	github.com/pmezard/go-difflib	 v1.0.0 \
	github.com/rifflock/lfshook	 v0.0.0-20180920164130-b9218ef580f5 \
	github.com/sirupsen/logrus	 v1.9.3 \
	github.com/stretchr/objx	 v0.1.0 \
	github.com/stretchr/testify	 v1.7.0 \
	golang.org/x/sys		 v0.12.0 \
	gopkg.in/check.v1		 v0.0.0-20161208181325-20d25e280405 \
	gopkg.in/yaml.v3		 v3.0.0-20200313102051-9f266ea9e77c

MODGO_MODFILES =	\
	github.com/davecgh/go-spew	 v1.1.0 \
	golang.org/x/sys		 v0.0.0-20220715151400-c0bba94af5f8

