# $OpenBSD$

COMMENT =	K Desktop Environment, mathematical function plotter
DISTNAME =	kmplot-${MODKDE_VERSION}

WANTLIB =  c m pthread stdc++
WANTLIB += lib/qt4/QtDBus lib/qt4/QtGui lib/qt4/QtNetwork lib/qt4/QtSvg
WANTLIB += lib/qt4/QtXml
WANTLIB += kdeui kio kparts nepomuk nepomukutils soprano

.include <bsd.port.mk>
