# $OpenBSD$

COMMENT =	screen gamma management for KDE
DISTNAME =	kgamma-${MODKDE_VERSION}

WANTLIB =  c m stdc++
WANTLIB += ICE SM X11 Xext Xxf86vm
WANTLIB += lib/qt4/QtDBus lib/qt4/QtGui lib/qt4/QtSvg
WANTLIB += kdeui

.include <bsd.port.mk>
