# $OpenBSD$

     SUBDIR =
# Base
     SUBDIR += libqtxdg			#BUILD	P
     SUBDIR += libsysstat		#BUILD	P
     SUBDIR += build-tools		#BUILD	P
# PcmanFM-qt
     SUBDIR += libfm-qt			#BUILD	P		UGLY PATCH
     SUBDIR += pcmanfm-qt		#BUILD 	P		UGLY PATCH
# LXQt
     SUBDIR += liblxqt			#BUILD	P
     SUBDIR += about			#BUILD	P
#     SUBDIR += admin			#NO_OPENBSD?
     SUBDIR += config			#BUILD	P		(NO KScreen)
     SUBDIR += globalkeys		#BUILD	P
     SUBDIR += l10n			#BUILD	P
     SUBDIR += notificationd		#BUILD	P
     SUBDIR += openssh-askpass		#BUILD	P
     SUBDIR += panel			#BUILD 	P		(NO ALSA)
     SUBDIR += policykit		#BUILD	P
     SUBDIR += powermanagement		#BUILD	P
     SUBDIR += qtplugin			#BUILD	P
     SUBDIR += runner			#BUILD	P		(NO muparser)
     SUBDIR += session			#BUILD	P
     SUBDIR += sudo			#BUILD	P
     SUBDIR += themes			#BUILD	P
# Related Releases
#     SUBDIR += lximage-qt
#     SUBDIR += compton-conf
#     SUBDIR += obconf-qt
#     SUBDIR += pavucontrol-qt
     SUBDIR += qterminal		#BUILD	P
     SUBDIR += qtermwidget		#BUILD	P
#     SUBDIR += qps			#NO_OPENBSD?
#     SUBDIR += screengrab

.include <bsd.port.subdir.mk>
