penBSD$

COMMENT =	PSGI handler for HTTP::Server::Simple

MODULES =	cpan
DISTNAME =	HTTP-Server-Simple-PSGI-0.14
CATEGORIES =	www
USE_GROFF =	Yes

MAINTAINER =	Wen Heping <wenheping@gmail.com>

# perl
PERMIT_PACKAGE_CDROM =	Yes
PERMIT_PACKAGE_FTP =	Yes
PERMIT_DISTFILES_CDROM =Yes
PERMIT_DISTFILES_FTP =	Yes

RUN_DEPENDS =		www/p5-HTTP-Server-Simple>=0.42

.include <bsd.port.mk>
