# $OpenBSD$

V =			2.6.0

CATEGORIES =		games

HOMEPAGE =		http://www.flightgear.org/

MAINTAINER =		Pascal Stumpf <Pascal.Stumpf@cubes.de>

# GPLv2+
PERMIT_PACKAGE_CDROM =	Yes

EXTRACT_SUFX =		.tar.bz2
